import { Tile } from "@/types/mario";

export const tiles: Tile[] = [
  {
    x: 0,
    y: 460,
    width: 400,
    height: 40,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },
  {
    x: 500,
    y: 460,
    width: 300,
    height: 40,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },
  {
    x: 900,
    y: 460,
    width: 300,
    height: 40,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },
  {
    x: 1300,
    y: 460,
    width: 400,
    height: 40,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },
  {
    x: 1800,
    y: 460,
    width: 400,
    height: 40,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },
  {
    x: 2300,
    y: 460,
    width: 400,
    height: 40,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },

  // 🔥 Hazards (lava pits between gaps)
  {
    x: 400,
    y: 460,
    width: 100,
    height: 40,
    color: "red",
    type: "hazard",
    imageSrc: "/world/Object/fire.png",
  },
  {
    x: 800,
    y: 460,
    width: 100,
    height: 40,
    color: "red",
    type: "hazard",
    imageSrc: "/world/Object/fire.png",
  },
  {
    x: 1200,
    y: 460,
    width: 100,
    height: 40,
    color: "red",
    type: "hazard",
    imageSrc: "/world/Object/fire.png",
  },
  {
    x: 2200,
    y: 460,
    width: 100,
    height: 40,
    color: "red",
    type: "hazard",
    imageSrc: "/world/Object/fire.png",
  },

  // 🪜 Platforms (ascending path)
  {
    x: 300,
    y: 400,
    width: 100,
    height: 20,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },
  {
    x: 500,
    y: 350,
    width: 100,
    height: 20,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },
  {
    x: 700,
    y: 300,
    width: 100,
    height: 20,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },
  {
    x: 950,
    y: 250,
    width: 120,
    height: 20,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },
  {
    x: 1150,
    y: 200,
    width: 120,
    height: 20,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },
  {
    x: 1350,
    y: 250,
    width: 120,
    height: 20,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },
  {
    x: 1550,
    y: 300,
    width: 120,
    height: 20,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },
  {
    x: 1750,
    y: 350,
    width: 120,
    height: 20,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },

  // ⚠️ Upper hazards (danger platforms)
  {
    x: 1050,
    y: 230,
    width: 60,
    height: 20,
    color: "red",
    type: "hazard",
    imageSrc: "/world/Object/fire.png",
  },
  {
    x: 1500,
    y: 320,
    width: 60,
    height: 20,
    color: "red",
    type: "hazard",
    imageSrc: "/world/Object/fire.png",
  },

  // 💰 Coin trails on platforms
  {
    x: 320,
    y: 360,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },
  {
    x: 520,
    y: 310,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },
  {
    x: 720,
    y: 260,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },
  {
    x: 970,
    y: 210,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },
  {
    x: 1170,
    y: 160,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },
  {
    x: 1370,
    y: 210,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },
  {
    x: 1570,
    y: 260,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },
  {
    x: 1770,
    y: 310,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },

  // 💰 Ground coins for exploration
  {
    x: 200,
    y: 420,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },
  {
    x: 600,
    y: 420,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },
  {
    x: 1000,
    y: 420,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },
  {
    x: 1400,
    y: 420,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },
  {
    x: 1900,
    y: 420,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },
  {
    x: 2400,
    y: 420,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },

  // 🧗 Secret high path (reward area)
  {
    x: 1850,
    y: 200,
    width: 100,
    height: 20,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },
  {
    x: 2050,
    y: 150,
    width: 100,
    height: 20,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },
  {
    x: 2250,
    y: 100,
    width: 100,
    height: 20,
    color: "green",
    type: "normal",
    imageSrc: "/world/Object/Crate.png",
  },
  {
    x: 2270,
    y: 60,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },
  {
    x: 2290,
    y: 60,
    width: 20,
    height: 20,
    color: "yellow",
    type: "coin",
    imageSrc: "/world/Object/coin.png",
  },

  // 🏁 Goal tile (reachable end)
  { x: 2600, y: 420, width: 60, height: 40, color: "purple", type: "goal",imageSrc: "/world/Object/flag.png", },

  // ☁️ Decorative tiles (no collision)
  {
    x: 200,
    y: 150,
    width: 100,
    height: 40,
    color: "white",
    type: "decoration",
    imageSrc: "/world/Object/Tree_2.png",
  },
  {
    x: 600,
    y: 120,
    width: 150,
    height: 50,
    color: "white",
    type: "decoration",
    imageSrc: "/world/Object/Tree_2.png",
  },
  {
    x: 1000,
    y: 180,
    width: 120,
    height: 40,
    color: "white",
    type: "decoration",
    imageSrc: "/world/Object/Tree_2.png",
  },
  {
    x: 1600,
    y: 130,
    width: 180,
    height: 60,
    color: "white",
    type: "decoration",
    imageSrc: "/world/Object/Tree_2.png",
  },

  // 🌳 Tree decorations
  {
    x: 400,
    y: 360,
    width: 30,
    height: 100,
    color: "#8B5A2B",
    type: "decoration",
    imageSrc: "/world/Object/Tree_2.png",
  },
  {
    x: 385,
    y: 310,
    width: 60,
    height: 60,
    color: "green",
    type: "decoration",
    imageSrc: "/world/Object/Tree_2.png",
  },

  // ⚙️ Moving hazard tiles
  {
    x: 900,
    y: 420,
    width: 30,
    height: 30,
    color: "red",
    type: "movingHazard",
    imageSrc: "/world/Object/fire.png",
    startY: 420,
    endY: 300,
    speedY: 1.5,
    direction: -1,
  },
  {
    x: 1300,
    y: 440,
    width: 30,
    height: 30,
    color: "red",
    type: "movingHazard",
    imageSrc: "/world/Object/fire.png",
    startY: 440,
    endY: 280,
    speedY: 2,
    direction: -1,
  },
];
